export const customerConstants = {
    CUSTOMERS_REQUEST: "CUSTOMERS_REQUEST",
    CUSTOMERS_FAILURE: "CUSTOMERS_FAILURE",
    CUSTOMERS_SUCCESS: "CUSTOMERS_SUCCESS",
};
export const transactionConstants = {
    TRANSACTIONS_REQUEST: "TRANSACTIONS_REQUEST",
    TRANSACTIONS_FAILURE: "TRANSACTIONS_FAILURE",
    TRANSACTIONS_SUCCESS: "TRANSACTIONS_SUCCESS",
};
export const transferConstants = {
    TRANSFER_REQUEST: "TRANSFER_REQUEST",
    TRANSFER_FAILURE: "TRANSFER_FAILURE",
    TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
    TRANSFER_RESET: "TRANSFER_RESET",
};
